[workspace]
resolver = "2"

members = [
    "datafusion-federation",
    "examples",
    "sources/sql",
    "sources/flight-sql",
]

[patch.crates-io]
# connectorx = { path = "../connector-x/connectorx" }
# datafusion = { path = "../arrow-datafusion/datafusion/core" }
# Pending next Datafusion release with `unnest` unparsing support
datafusion = { git = "https://github.com/spiceai/datafusion.git", rev = "0bad328656a07fd5ab899186462b09e119e21f90" }

[workspace.package]
version = "0.1.6"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"


[workspace.dependencies]
async-trait = "0.1.77"
async-stream = "0.3.5"
futures = "0.3.30"
datafusion = "43"
datafusion-substrait = "43"
arrow-json = "53"
