[workspace]
resolver = "2"

members = [
    "datafusion-federation"
]

[workspace.package]
version = "0.4.2"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/datafusion-contrib/datafusion-federation"

[workspace.dependencies]
arrow-json = "54"
async-stream = "0.3.5"
async-trait = "0.1.83"
datafusion = "46.0.1"
datafusion-federation = { path = "./datafusion-federation", version = "0.4.2" }
futures = "0.3.31"
tokio = { version = "1.41", features = ["full"] }

#[patch.crates-io]
#duckdb = { git = "https://github.com/spiceai/duckdb-rs.git", rev = "2e24b958e44ec7419290249e27a15f1a19703fff" }

