[workspace]
resolver = "2"

members = [
    "datafusion-federation",
    "examples",
    "sources/sql",
    "sources/flight-sql",
]

[patch.crates-io]
# connectorx = { path = "../connector-x/connectorx" }
# datafusion = { path = "../arrow-datafusion/datafusion/core" }

[workspace.package]
version = "0.1.3"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"


[workspace.dependencies]
async-trait = "0.1.77"
datafusion = { git = "https://github.com/spiceai/datafusion.git", rev = "ea1176ae08dd0f94c99ef7f1d7dc989e383a3586" }
datafusion-substrait = { git = "https://github.com/spiceai/datafusion.git", folder = "datafusion/substrait", rev = "ea1176ae08dd0f94c99ef7f1d7dc989e383a3586" }